#!/bin/bash

# bash_prompt
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
	platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
	platform='osx'
fi

machine_name='unknown'
machine_name=`scutil --get ComputerName`


unset PROMPT_COMMAND

# Set a fancy prompt, slightly different for each OS.
#if [[ $platform == 'osx' ]]; then
#    PROMPT_TITLE='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/~}\007"'
#    export PROMPT_COMMAND="${PROMPT_COMMAND} ${PROMPT_TITLE}; "
#elif [[ $platform == 'linux' ]]; then
#    PROMPT_TITLE='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/~}\007"'
#    export PROMPT_COMMAND="${PROMPT_COMMAND}; "
#fi

# OLD:
# set a fancy prompt
#export PS1='\h:\w\$ '
#export PS1="[\h] \[\e[0;31m\]\u\[\e[0m\]@\[\e[0;32m\][\w]\[\e[0m\]: "
#export PS1="[\h] \[\033[0;31m\]\W\[\033[0m\]  $\[\e]2; [\h]\]$PWD\[\a\]\[\e]1;\]$(basename $(dirname $PWD)) /\W\[\a\] "
GREEN="\[\e[0;32m\]"
RED="\[\e[0;31m\]"
PLAIN="\[\e[m\]"

if [[ $machine_name == 'huracan' ]]; then
    PS1="${PLAIN}[huracan] ${RED}\W${PLAIN} $ "
else
    PS1="${PLAIN}[\h] ${RED}\W${PLAIN} $ "
fi

