#!/bin/bash

# bash_config

# Make MacVim the visual editor
export VISUAL='mvim -f'

# Make vim the default editor
export EDITOR="vim"

# make ls display colors, reinforce with CLICOLOR and LSCOLORS
export CLICOLOR=1
 
# LSCOLORS order: DIR, SYM_LINK, SOCKET, PIPE, EXE, BLOCK_SP
# CHAR_SP, EXE_SUID, EXE_GUID, DIR_STICKY, DIR_WO_STICKY
# a = black, b = red, c = green, d = brown, e = blue,
# f = magenta g = cyan, h = light gray, x = default
# lowercase is bold
 export LSCOLORS=ExFxBxDxCxegedabagacad

MKL_NUM_THREADS=1
export MKL_NUM_THREADS
 
source `brew --prefix`/Library/Contributions/brew_bash_completion.sh

# Define the GRADS script folder
export GASCRP=$HOME/bighorn
